### ISSUE TITLE
Bug in alexnet 

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3torch#15]
currently the early stopping as implemented in alexnet does not respect the row_roles, consider, the following example: 
(Update to the latest `mlr3` dev-version before). In the example above, the holdout set is specified, which as defined [here](https://mlr3.mlr-org.com/reference/Task.html) should be an independent data set. However the way the validation data is sampled, it can happen that it is used for early stopping. 

``` r
library(mlr3)
task = tsk("iris")
task$row_roles$use = c(1:10, 21:150)
task$row_roles$holdout = c(11:20)
sample(task$nrow, 100)
#>   [1]  62  29   1 140 107  81   9  25  53  80 136  40  66  46  20  78 131  60
#>  [19] 113 105 123  94 125  16 112  59  61 122  36 111 104 134  33  95 137 129
#>  [37]  49  24 138  32 121   6   8  19  42 133  64  38  48  97  51  35  47 101
#>  [55]  27  71  56  44  72  41  82  91  65  88 108 103  85  39 119  57  21  37
#>  [73] 118 130 114  31  77  75 120 139  58  99 132  26  63  14  18  68  93  13
#>  [91]  90   7 116  12  74  45 115 127  96 102
```

<sup>Created on 2022-02-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jemus42** [comment]
So the dataloaders here https://github.com/mlr-org/mlr3torch/blob/image-task/R/utils-tasks.R#L70-L76 should just get their row ids from `task$row_roles$use` and `task$row_roles$holdout` respectively then?  

If no holdout set is defined in the task beforehand but a validation split is requested, is there a benefit in assigning the `row_roles` internally? 🤔 
In any case, for the learners to actually early top, I still need to add the corresponding [callback](https://mlverse.github.io/luz/reference/luz_callback_early_stopping.html), and it's arguments need to be parameterized,
I haven't dealt with more callbacks yet because this was another case where I wasn't sure if they should be explicitly noted in the `ParamSet` including their arguments or if there should be just a callbacks `ParamUty` that takes a list of functions 🙃
